minimumReleaseAgeExclude:
  - "@sveltejs/kit@2.70.0"
  - svelte@5.56.6
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vite-plus: 0.2.5
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  esbuild: true
  sharp: true
